project:
  type: website

website:
  title: "sinpepperoni"
  site-url: "https://sinpepperoni.com/"
  description: "Descubriendo la economía sin pepperoni."
  back-to-top-navigation: true
  sidebar:
    logo: "download.png"
    style: "docked"
    search: true
    contents:
      - text: "About me"
        href: about.qmd    
      - text: "Econometrics"
        href: econometric-series.qmd
      - text: "Climate economics"
        href: climate-economics-series.qmd
  body-footer: footer.html
format:
  html:
    theme: theme.scss
    mainfont: system-ui
    fontcolor: black
    minimal: false
    smooth-scroll: true
    fontsize: 0.8em
    grid:
      gutter-width: 4.0rem